version: "3.8"

services:
  backend:
    container_name: starburger-backend
    restart: always
    build:
        context: .
        dockerfile: ./src/backend/docker/django/Dockerfile
        args:
          - APP_ENV=dev
    command: python manage.py runserver 0.0.0.0:8080
    environment:
      SECRET_KEY: ${SECRET_KEY-REPLACE_ME}
      DEBUG: ${DEBUG-TRUE}
      DATABASE_URL: ${DATABASE_URL-postgres://app_dev:OwOtBdfep9Frut@db:5432/app_dev}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS-127.0.0.1,localhost}
      GIT_PYTHON_REFRESH: ${GIT_PYTHON_REFRESH-quiet}
      YANDEX_GEOCODER_APIKEY: ${YANDEX_GEOCODER_APIKEY-REPLACE_ME}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME-superuser}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL-superuser@super.email}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD-superpassword}
    volumes:
      - ./src/backend:/opt/app/
      - ./src/backend/bundles:/opt/app/bundles
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    container_name: starburger-frontend
    restart: always
    build:
        context: .
        dockerfile: ./src/frontend/docker/Dockerfile
    ports:
      - "1234:1234"
    depends_on:
      - backend

  db:
    image: postgres:12.0-alpine
    container_name: starburger_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB-app_dev}
      POSTGRES_USER: ${POSTGRES_USER-app_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBdfep9Frut}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backup:/backup


volumes:
  postgres_data:
