# Generated by Django 3.2.4 on 2021-09-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20210907_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], default='cash', max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
