# Generated by Django 3.2.4 on 2021-09-15 04:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20210915_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
